CREATE TABLE IF NOT EXISTS db_middle.BASE_ENERGY_CONSUMPTION_RATE_MST (
    FISCAL_YEAR VARCHAR(4),
    MENU_NUM INT,
    MENU_ITEM STRING,
    ENERGY_CONSUMPTION_CATEGORY STRING,
    CORRECTION_CATEGORY_USAGE STRING,
    CORRECTION_CATEGORY_RANGE STRING,
    BASE_ENERGY_CONSUMPTION_RATE DECIMAL(5,4),
    CREATION_DATETIME TIMESTAMP,
    CREATOR VARCHAR(50)
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/hd/hd-volume-01/middle/BASE_ENERGY_CONSUMPTION_RATE_MST';