CREATE TABLE IF NOT EXISTS db_middle.KUBUN_MST(
    IDENTIFY_CD STRING,
    CATEGORY_CD STRING,
    CATEGORY_NAME STRING,
    SUB_CATEGORY_CD STRING,
    SUB_CATEGORY_NAME STRING,
    KBN_CD STRING,
    KBN_NAME STRING,
    KBN_SORT INT,
    CREATION_DATETIME TIMESTAMP,
    CREATOR STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/hd/hd-volume-01/middle/KUBUN_MST';
