CREATE TABLE IF NOT EXISTS db_middle.EMISSION_COEFFICIENT_MST (
    REGISTRATION_NUMBER VARCHAR(5),
    ELECTRIC_UTILITY_COMPANY_NAME VARCHAR(100),
    BASELINE_EMISSION_FACTOR DECIMAL(7,6),
    ADJUSTED_EMISSION_FACTOR DECIMAL(7,6),
    FISCAL_YEAR VARCHAR(4),
    MENU_ID VARCHAR(6),
    MENU_NAME VARCHAR(50),
    START_DATE DATE,
    END_DATE DATE,
    CREATION_DATETIME TIMESTAMP,
    CREATOR VARCHAR(50)
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/hd/hd-volume-01/middle/EMISSION_COEFFICIENT_MST'; 
