CREATE TABLE IF NOT EXISTS db_middle.CONVERSION_COEFFICIENT_MST (
    ENERGY_CODE VARCHAR(6),
    CATEGORY VARCHAR(10),
    ENERGY_NAME VARCHAR(20),
    ENERGY_UNITS VARCHAR(20),
    UNIT_HEAT_GENERATION DECIMAL(4,2),
    UNIT_HEAT_GENERATION_UNITS VARCHAR(10),
    EMISSION_COEFFICIENT DECIMAL(5,4),
    EMISSION_COEFFICIENT_UNITS VARCHAR(10),
    PRIMARY_EMISSION_COEFFICIENT DECIMAL(5,4),
    PRIMARY_EMISSION_COEFFICIENT_UNITS VARCHAR(10),
    CONVERSION_VALUE DECIMAL(4,3),
    CONVERSION_VALUE_UNITS VARCHAR(10),
    START_DATE DATE,
    END_DATE DATE,
    FISCAL_YEAR STRING,
    CREATION_DATETIME TIMESTAMP,
    CREATOR VARCHAR(50)
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/hd/hd-volume-01/middle/CONVERSION_COEFFICIENT_MST'; 
