CREATE TABLE IF NOT EXISTS db_middle.SCATTER_PLOT_AGGREGATE_INFORMATION (
    BANK_CODE VARCHAR(4),
    CORPORATE_NUMBER VARCHAR(13),
    BUILDING_USAGE VARCHAR(2),
    FISCAL_YEAR VARCHAR(4),
    CONSUMPTION_QUANTITY_X_AXIS_START VARCHAR(50),
    CONSUMPTION_QUANTITY_Y_AXIS_START VARCHAR(3),
    CONSUMPTION_QUANTITY_X_AXIS_END VARCHAR(50),
    CONSUMPTION_QUANTITY_Y_AXIS_END VARCHAR(3),
    ORIGINAL_CONSUMPTION_UNIT_X_AXIS_START VARCHAR(50),
    ORIGINAL_CONSUMPTION_UNIT_Y_AXIS_START DECIMAL(12,2),
    ORIGINAL_CONSUMPTION_UNIT_X_AXIS_END VARCHAR(50),
    ORIGINAL_CONSUMPTION_UNIT_Y_AXIS_END DECIMAL(12,2),
    AXIS_X_COORDINATE_A DECIMAL(12,2),
    AXIS_Y_COORDINATE_A DECIMAL(12,2),
    AXIS_X_COORDINATE_B1 DECIMAL(12,2),
    AXIS_Y_COORDINATE_B1 DECIMAL(12,2),
    AXIS_X_COORDINATE_B2 DECIMAL(12,2),
    AXIS_Y_COORDINATE_B2 DECIMAL(12,2),
    AXIS_X_COORDINATE_C DECIMAL(12,2),
    AXIS_Y_COORDINATE_C DECIMAL(12,2),
    CREATION_DATETIME TIMESTAMP,
    CREATOR VARCHAR(50)
)
PARTITIONED BY (
    PART_BANK_CODE VARCHAR(4),
    PART_CORPORATE_NUMBER VARCHAR(13),
    PART_FISCAL_YEAR VARCHAR(4)
)
STORED AS PARQUET
LOCATION '/hd/hd-volume-01/middle/SCATTER_PLOT_AGGREGATE_INFORMATION';
