CREATE TABLE IF NOT EXISTS db_middle.ENERGY_CONSUMPTION_DESTINATION_MST (
    BUILDING_USAGE VARCHAR(2),
    FISCAL_YEAR VARCHAR(4),
    ENERGY_CATEGORY_DIV VARCHAR(2),
    ENERGY_CATEGORY_NAME VARCHAR(50),
    ENERGY_SUB_DIV VARCHAR(2),
    ENERGY_SUB_NAME VARCHAR(50),
    VALUE DECIMAL(10,4),
    CREATION_DATETIME TIMESTAMP,
    CREATOR VARCHAR(50)
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
LOCATION '/hd/hd-volume-01/middle/ENERGY_CONSUMPTION_DESTINATION_MST';