CREATE TABLE IF NOT EXISTS db_middle.AREA_INFO_MST (
    AREA_ID VARCHAR(16),
    CORPORATE_NUMBER VARCHAR(13),
    AREA_INFORMATION VARCHAR(100),
    CORPORATE_ID VARCHAR(6),
    CREATION_DATETIME TIMESTAMP,
    CREATOR VARCHAR(50)
)
STORED AS PARQUET
LOCATION '/hd/hd-volume-01/middle/AREA_INFO_MST';
