CREATE TABLE IF NOT EXISTS db_middle.ELECTRICITY_CO2_EMISSION_MST (
    FISCAL_YEAR VARCHAR(4),
    FIXED_PATTERN VARCHAR(100),
    ELECTRIC_POWER_2030_PATTERN VARCHAR(100),
    CUSTOM_SETTING_PATTERN VARCHAR(50),
    NATIONAL_AVERAGE_PATTERN VARCHAR(50),
    CREATION_DATETIME TIMESTAMP,
    CREATOR VARCHAR(50)
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
LOCATION '/hd/hd-volume-01/middle/ELECTRICITY_CO2_EMISSION_MST';

ALTER TABLE db_middle.ELECTRICITY_CO2_EMISSION_MST SET TBLPROPERTIES("skip.header.line.count"="1");