CREATE TABLE IF NOT EXISTS db_middle.COUNTERMEASURE_MST (
    FISCAL_YEAR VARCHAR(4),
    MENU_NUM INT,    
    MENU_ITEM VARCHAR(100),   
    COUNTERMEASURE_MENU VARCHAR(10),   
    COUNTERMEASURE_FLAG INT,   
    CREATION_DATETIME TIMESTAMP,
    CREATOR VARCHAR(50)    
)   
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
LOCATION '/hd/hd-volume-01/middle/COUNTERMEASURE_MST';
