CREATE TABLE IF NOT EXISTS db_middle.JAPAN_INDUSTRIAL_CLASSIFICATION_MST (
    LARGE_CATEGORY_CODE VARCHAR(2),
    LARGE_CATEGORY_NAME STRING,
    MEDIUM_CATEGORY_CODE VARCHAR(3),
    MEDIUM_CATEGORY_NAME STRING,
    SMALL_CATEGORY_CODE VARCHAR(4),
    DETAIL_CATEGORY_CODE VARCHAR(4),
    INDUSTRY_CLASSIFICATION_NAME VARCHAR(100),
    START_DATE DATE,
    END_DATE DATE,
    CREATION_DATETIME TIMESTAMP,
    CREATOR VARCHAR(50)
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/hd/hd-volume-01/middle/JAPAN_INDUSTRIAL_CLASSIFICATION_MST';

