#換算係数マスタ
ALTER TABLE CONVERSION_COEFFICIENT_MST ADD COLUMNS (YEAR VARCHAR(4));

#電力会社の排出係数マスタ
ALTER TABLE EMISSION_COEFFICIENT_MST CHANGE COLUMN MENU_ID ELECTRICITY_MENU_ID VARCHAR(3);
ALTER TABLE EMISSION_COEFFICIENT_MST CHANGE COLUMN MENU_NAME ELECTRICITY_MENU_NAME VARCHAR(50);

#入力情報
ALTER TABLE APPLICATION_BASIC_INFORMATION CHANGE COLUMN UTILIZATION_APPROVAL_DATE_CORPORATE UTILIZATION_APPROVAL_DATE_CORPORATE VARCHAR(8);
ALTER TABLE APPLICATION_BASIC_INFORMATION CHANGE COLUMN PHONE_NUMBER_LOCAL_BANK PHONE_NUMBER_LOCAL_BANK VARCHAR(15);
ALTER TABLE APPLICATION_BASIC_INFORMATION CHANGE COLUMN PHONE_NUMBER_CORPORATE PHONE_NUMBER_CORPORATE VARCHAR(15);

#エネルギー費用
ALTER TABLE TEPCO_ENEGRY_SOLUTION_INFO CHANGE COLUMN LPG_GAS_LOW_CALORIFIC LPG_GAS_LOW_CALORIFIC DECIMAL(6,1);

#ソリューション計算結果
ALTER TABLE SOLUTION_CALCULATION_RESULTS CHANGE COLUMN HOT_WATER_HEAT_LOAD_OTHER DAY_HOT_WATER_HEAT_LOAD_OTHER DECIMAL(6,0);
