CREATE TABLE IF NOT EXISTS db_middle.FILE_PROCESS_STATUS(
    FILE_NAME STRING,
    FILE_PATH STRING,
    FILE_TYPE STRING,
    STATUS STRING,
    CREATION_DATETIME TIMESTAMP,
    CREATOR STRING
)
STORED AS PARQUET
LOCATION '/hd/hd-volume-01/middle/FILE_PROCESS_STATUS';
